services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: power2plant
      POSTGRES_PASSWORD: power2plant
      POSTGRES_DB: power2plant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
