#!/usr/bin/env bash
# Called by systemd power2plant-staging-deploy.service when the "DB Integrity"
# workflow_run completes successfully on a release/* branch (via GitHub webhook).
# DEPLOY_USERNAME, PROJECT_PATH (staging), PROD_PATH, and STAGING_DUMP_FILE are
# injected via Environment= in the service unit, generated by scripts/server/setup.sh.
set -euo pipefail

: "${DEPLOY_USERNAME:?not set — run scripts/server/setup.sh to reinstall the service unit}"
: "${PROJECT_PATH:?not set — run scripts/server/setup.sh to reinstall the service unit}"
: "${PROD_PATH:?not set — run scripts/server/setup.sh to reinstall the service unit}"
: "${STAGING_DUMP_FILE:?not set — run scripts/server/setup.sh to reinstall the service unit}"

BRANCH_FILE="/run/p2p/staging-deploy.branch"

if [[ ! -f "$BRANCH_FILE" ]]; then
  echo "Error: $BRANCH_FILE missing — webhook should have written the ref here" >&2
  exit 1
fi

BRANCH=$(cat "$BRANCH_FILE")
rm -f "$BRANCH_FILE" /run/p2p/staging-deploy.trigger

cd "$PROJECT_PATH"
sudo -u "$DEPLOY_USERNAME" git fetch --prune origin
sudo -u "$DEPLOY_USERNAME" git checkout -B "$BRANCH" "origin/$BRANCH"

# Clone or update invoice-service if INVOICE_SERVICE_REPO is set in .env
INVOICE_SERVICE_REPO=$(grep -E '^INVOICE_SERVICE_REPO=' "${PROJECT_PATH}/.env" 2>/dev/null | cut -d= -f2- | tr -d '"' || true)
if [[ -n "${INVOICE_SERVICE_REPO}" ]]; then
  if [[ -d "${PROJECT_PATH}/invoice-service/.git" ]]; then
    sudo -u "$DEPLOY_USERNAME" git -C "${PROJECT_PATH}/invoice-service" pull origin main
  else
    sudo -u "$DEPLOY_USERNAME" git clone "$INVOICE_SERVICE_REPO" "${PROJECT_PATH}/invoice-service"
  fi
fi

# Start DB only first so bootstrap can restore the dump before the app migrates.
# This ensures prisma migrate deploy always runs against a clean known-good state.
sudo -u "$DEPLOY_USERNAME" docker compose up -d db invoice-db 2>/dev/null || \
  sudo -u "$DEPLOY_USERNAME" docker compose up -d db

"${PROJECT_PATH}/scripts/server/staging-seed-bootstrap.sh"

# Now bring up the full stack. App container runs prisma migrate deploy against
# the freshly restored DB — no stuck migrations possible.
sudo -u "$DEPLOY_USERNAME" docker compose up -d --build
