#!/usr/bin/env bash
# Called by systemd power2plant-staging-deploy.service when the "DB Integrity"
# workflow_run completes successfully on a release/* branch (via GitHub webhook).
# DEPLOY_USERNAME, PROJECT_PATH (staging), and PROD_PATH are injected via
# Environment= in the service unit, generated by scripts/server/setup.sh.
set -euo pipefail

: "${DEPLOY_USERNAME:?not set — run scripts/server/setup.sh to reinstall the service unit}"
: "${PROJECT_PATH:?not set — run scripts/server/setup.sh to reinstall the service unit}"
: "${PROD_PATH:?not set — run scripts/server/setup.sh to reinstall the service unit}"

BRANCH_FILE="/run/p2p/staging-deploy.branch"

if [[ ! -f "$BRANCH_FILE" ]]; then
  echo "Error: $BRANCH_FILE missing — webhook should have written the ref here" >&2
  exit 1
fi

BRANCH=$(cat "$BRANCH_FILE")
rm -f "$BRANCH_FILE" /run/p2p/staging-deploy.trigger

cd "$PROJECT_PATH"
sudo -u "$DEPLOY_USERNAME" git fetch --prune origin
sudo -u "$DEPLOY_USERNAME" git checkout -B "$BRANCH" "origin/$BRANCH"
sudo -u "$DEPLOY_USERNAME" docker compose up -d --build

"${PROJECT_PATH}/scripts/server/staging-seed-bootstrap.sh"
